services:
  - name: backend
    type: web
    env: python
    # runtime read from runtime.txt
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
